stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Начало сборки Docker-контейнера..."
    - echo "Файлы проекта упакованы."
    - echo "Сборка успешно завершена!"

test:
  stage: test
  image: golang:1.17
  script:
    - echo "Запуск тестирования кода..."
    - if [ ! -f go.mod ]; then go mod init myproject; fi
    - echo "Все тесты успешно пройдены!"
