stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    # Указываем точный адрес демона Docker
    DOCKER_HOST: "tcp://docker:2375"
    # Отключаем TLS, так как раннер подключается по обычному tcp-порту 2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build .

test:
  stage: test
  image: golang:1.17
  script:
    - if [ ! -f go.mod ]; then go mod init myproject; fi
    - go test ./...
